"""Capture a clean, tested development environment or verify its exact pins.

Run only inside the project's clean virtualenv after deliberate dependency
upgrades. Never resolves or upgrades packages by itself.
"""
import argparse
from importlib.metadata import distributions
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
TOOLS = {"pip", "setuptools", "wheel", "uv"}


def normalize(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def in_virtualenv():
    return sys.prefix != sys.base_prefix


def installed():
    result = {}
    for package in distributions():
        name = normalize(package.metadata["Name"])
        if name in TOOLS:
            continue
        direct = package.read_text("direct_url.json")
        if direct:
            raise ValueError(f"{name} is installed from a direct URL; use a reproducible package-index release")
        result[name] = package.version
    return result


def parse(text):
    result = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if not re.fullmatch(r"[A-Za-z0-9_.-]+==[A-Za-z0-9_.+!-]+", line):
            raise ValueError(f"Not an exact pin: {line}")
        name, version = line.split("==")
        name = normalize(name)
        if name in result:
            raise ValueError(f"Duplicate constraint: {name}")
        result[name] = version
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Replace constraints with the reviewed environment; upgrades are explicit")
    args = parser.parse_args()
    # Every installed distribution is compared, so the environment must hold
    # the project's and nothing else. A shared interpreter never does: the
    # GitHub Windows image's Python ships pipx and its dependencies, which
    # failed this check as "unpinned" with nothing wrong in the project.
    if not in_virtualenv():
        raise SystemExit(f"{sys.executable} is not a virtualenv; run this inside the project's "
                         "clean one (see docs/dependency-upgrades.md)")
    current = installed()
    path = ROOT / "constraints.txt"
    if args.write:
        # Preserve pins absent on this OS (e.g. colorama on macOS). CI verifies
        # the complete Windows/macOS matrix before an upgrade is accepted.
        pins = parse(path.read_text(encoding="utf-8")) if path.exists() else {}
        pins.update(current)
        path.write_text("# Generated by scripts/lock_dependencies.py --write; review and test upgrades.\n" +
                        "".join(f"{name}=={version}\n" for name, version in sorted(pins.items())), encoding="utf-8")
        print("Constraints written. Review the diff, run pip check, and test every supported platform.")
    else:
        pins = parse(path.read_text(encoding="utf-8"))
        mismatches = [name for name, version in current.items() if pins.get(name) != version]
        if mismatches:
            raise SystemExit("Unpinned or changed packages: " + ", ".join(sorted(mismatches)))
        print("Installed dependencies match the exact constraints.")


if __name__ == "__main__":
    main()
